config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'registrations'}
  
  
  resources :quotes do
    resources :bids
  end
  resources :profiles

  resources :bids do
    resources :comments
  end

  resources :consultations

  match "quote", to: "quotes#quote", via: 'get'

  get "comments/index"

  get "comments/new"

  resources :states
  resources :seo_pages

  get 'divorce/:slug', to: 'states#show', as: 'state_show' 

  get ':state/:city/:id', to: 'seo_pages#show', as: 'seo_show'

  root to: 'tours#websites'

  scope '/lawyers' do
    get 'websites', to: 'tours#websites'
  end

  match "home", to: 'pages#home' , via: 'get'
    

end

app/models/quote.rb
class Quote < ActiveRecord::Base
	has_many :bids
	belongs_to :user
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
	before_action :set_quote, only: [:show, :edit, :update, :destroy]
	before_filter :verify_vendor, only: [:index]
	def new
		@quote = Quote.new

	    respond_to do |format|
	      format.html # new.html.erb
	      format.json { render json: quote }
	    end
	end

	def create
		if current_user
			@quote = current_user.quotes.new(quote_params)
			@quote.user_id = current_user.id
			@quote.email = current_user.email
		else
			@quote = Quote.new(quote_params)
		end

	    respond_to do |format|
	      if @quote.save
	        format.html { redirect_to @quote, notice: 'Your Quote Has Been Processed.' }
	        format.json { render action: 'show', status: :created, location: @quote }
	      else
	        format.html { render action: 'new' }
	        format.json { render json: @quote.errors, status: :unprocessable_entity }
	      end
	    end

	end

	def index
		@quotes = Quote.order("id DESC").all
	end

	def quote
		if signed_in?
			if current_user.quotes.last.present?
				@quote = current_user.quotes.last
				redirect_to quote_path(@quote)
			else
				redirect_to new_quote_path
			end
		else
			redirect_to new_quote_path
		end
	end

	def show
		if signed_in?
			if current_user.id == @quote.user_id
				@bids = @quote.bids
			else
				redirect_to root_path
			end
		else
			redirect_to root_path
		end
	end

	private

	def set_quote
		@quote = Quote.find(params[:id])
	end

	def quote_params
      params.require(:quote).permit(:email, :name, :field, :description, :location, :user_id)
    end


end

app/views/quotes/_form.html.erb
<div class="row">
	<div class="col-sm-8 col-sm-offset-3">
		<div class="quote-form">
			<%= form_for @quote do |f| %>
				<% unless signed_in? %>
					<h3 class="quote_label">Enter Your Email</h3>
					<%= f.text_field(:email, class: "quote_input") %><br/>
				<% end %>
				<h3 class="quote_label">Name</h3>
				<%= f.text_field(:name, class: "quote_input") %><br/>

				<h3 class="quote_label">Type</h3>
				<%= f.select :field, options_for_select([["Divorce", "Divorce"], ["Pre-Nup", "Pre-Nup"], ["Legal Separation", "Legal Separation"], ["Annulment", "Annulment"]]) %><br/>

				<h3 class="quote_label">What Are Your Legal Needs?</h3>
				<%= f.text_area(:description, class: "quote_textarea") %><br/>

				<h3 class="quote_label">Location</h3>
				<%= f.text_field(:location, class: "quote_input", placeholder: "Please Enter Your Zip Code") %><br/><br/>


				<%= f.submit "Get A Quote", class: "quote-button" %>
			<% end %>
		</div>
	</div>
</div>

app/views/quotes/index.html.erb
<div class="quote-header-show">
	<div class="container-fluid pad-top-bot">
		<div class="clearfix left">
			<a class="pic-padding left" style="width: 60px;">
				<img src="https://assembly.firesize.com/120x120/g_center/https://d1015h9unskp4y.cloudfront.net/attachments/bda9dba4-57d1-417e-a592-6fe5efbdd9d6/InstajobsLogo-01.jpg" width="60" height="60">
			</a>
			<div class="overflow-hidden">
				<h2 class="marg-bot-top-0">Lawyer Dashboard</h2>
				<h4 class="marg-bot-top-0"><%= current_user.email %> </h4>
			</div>

		</div>
	</div>
	<div class="border-top">
		<div class="tab-container">
			<ul class= "new-nav--tabs">
				<li class="new-tab">Quotes Available</li>
				<li class="new-tab-unselect"><%= link_to "Bids Placed", bids_path %></li>
			</ul>
		</div>
	</div>
</div>
<div class="container-fluid grey-quote-block">
	<div class="col-sm col-sm-8 px3">
		<div class="col-xs-12">
			<% @quotes.each do |q| %>
				<div class="bg-white bid-shadow">
					<div class="bid-header">
						<h4><%= link_to q.name, new_quote_bid_path(q.id) %></h4>
						<h4>Location: <%= q.location %></h4>
					</div>
					<div class="border-top bid-header">
						<p><%= q.description %></p>
					</div>
					<div class="border-top bid-header">
						<div class="left" style="padding-right: 10px">
							<img class="bg-gray-6" src="https://gravatar.com/avatar/d377714ee6c1f97fa2c17ac9fa8825a9?d=https%3A%2F%2Fassembly.com%2Fassets%2Fdefault_avatar.png&amp;s=288" width="24" height="24" style="max-width:24px;max-height:24px;">
						</div>
						<div style="padding-bottom: 10px; padding-left: 5px;">
							Created this Quote on <%= q.created_at.strftime("%b %d") %>
						</div>

					</div>
				</div>
			<% end %>
		</div>
	</div>
	<div class="col-sm col-sm-4 px3">
		
	</div>
</div>

app/views/quotes/new.html.erb
<div class="container-fluid grey">
	<h1 class="quote-header">Get Quotes from Qualified Family Law Professionals</h1>
	<%= render 'form' %>
</div>

app/views/quotes/show.html.erb
<div class="quote-header-show">
	<div class="container-fluid pad-top-bot">
		<div class="clearfix left">
			<a class="pic-padding left" style="width: 60px;">
				<img src="https://assembly.firesize.com/120x120/g_center/https://d1015h9unskp4y.cloudfront.net/attachments/bda9dba4-57d1-417e-a592-6fe5efbdd9d6/InstajobsLogo-01.jpg" width="60" height="60">
			</a>
			<div class="overflow-hidden">
				<h2 class="marg-bot-top-0"><%= @quote.name  %></h2>
				<h4 class="marg-bot-top-0"><%= @quote.location %> </h4>
			</div>

		</div>
	</div>
	<div class="border-top">
		<div class="tab-container">
			<ul class= "new-nav--tabs">
				<li class="new-tab">Bids  </li>

			</ul>
		</div>
	</div>
</div>
<div class="container-fluid grey-quote-block">
	<div class="col-sm col-sm-8 px3">
		<div class="col-xs-12">
			
			<% if @bids != [] %> 
				<% @bids.each do |b| %>
					<div class="bg-white bid-shadow">
						<div class="bid-header">
							<h4><%= link_to b.name, quote_bid_path(@quote, b) %></h4>
							<h4>Bid Amount: $<%= b.amount %> </h4>
						</div>
						<div class="border-top bid-header">
							<p><%= b.description %></p>
						</div>
						<div class="border-top bid-header">
							<div class="left" style="padding-right: 10px">
								<img class="bg-gray-6" src="https://gravatar.com/avatar/d377714ee6c1f97fa2c17ac9fa8825a9?d=https%3A%2F%2Fassembly.com%2Fassets%2Fdefault_avatar.png&amp;s=288" width="24" height="24" style="max-width:24px;max-height:24px;">
							</div>
							<div style="padding-bottom: 10px; padding-left: 5px;">
								<%= b.user.email %> submitted this Bid on <%= b.created_at.strftime("%b %d") %>
							</div>

						</div>
					</div>
				<% end %>
			<% else %>
				<div class="bg-white bid-shadow">
					<div class="bid-header" style="padding-bottom: 10px">
						<h4>You don't have any Bids Yet.  We'll let you know when your first bids come in.</h4>
					</div>
				</div>
			<% end %>



		</div>
	</div>
	<div class="col-sm col-sm-4 px3">
		<div class="bg-white bid-shadow">
			<div class="bid-header">
				<h2>Quote Overview</h2>
				<h4>Name: <%= @quote.name %></h4>
				<h4>Location: <%= @quote.location %></h4>
			</div>
			<div class="border-top bid-header" style="padding-bottom: 10px;">
				<h4>Type: <%= @quote.field %></h4>
				<p><%= @quote.description %></p>
			</div>

		</div>
	</div>
</div>