config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'registrations'}
  
  
  resources :quotes do
    resources :bids
  end
  resources :profiles

  resources :bids do
    resources :comments
  end

  resources :consultations

  match "quote", to: "quotes#quote", via: 'get'

  get "comments/index"

  get "comments/new"

  resources :states
  resources :seo_pages

  get 'divorce/:slug', to: 'states#show', as: 'state_show' 

  get ':state/:city/:id', to: 'seo_pages#show', as: 'seo_show'

  root to: 'tours#websites'

  scope '/lawyers' do
    get 'websites', to: 'tours#websites'
  end

  match "home", to: 'pages#home' , via: 'get'
    

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	has_attached_file :avatar, :styles => {:medium => "225x225#", :thumb => "90x90>", :mini => "40x40#"}, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :verify_admin, only: [:new, :edit, :update, :destroy]
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @title = "Divorce Lawyer - #{@profile.name} from #{@profile.city}, #{@profile.state}"
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def verify_admin
    unless current_user.admin? == true
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :name, :email, :claimed, :description, :blurb, :bar_id, :state, :phone_number, :law_school, :avatar, :city, :address_line_1, :scrape_url, :zip_code, :address_line_2)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :claimed %><br>
    <%= f.check_box :claimed %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :blurb %><br>
    <%= f.text_field :blurb %>
  </div>
  <div class="field">
    <%= f.label :bar_id %><br>
    <%= f.text_field :bar_id %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :law_school %><br>
    <%= f.text_field :law_school %>
  </div>

  <div class="field">
    <%= f.label :scrape_url %><br>
    <%= f.text_field :scrape_url %>
  </div>

  <div>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container-fluid">
	<h1>Editing Profile</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @profile %> |
	<%= link_to 'Back', profiles_path %>
</div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Email</th>
      <th>Claimed</th>
      <th>Description</th>
      <th>Blurb</th>
      <th>Bar</th>
      <th>State</th>
      <th>Phone number</th>
      <th>Law school</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user_id %></td>
        <td><%= profile.name %></td>
        <td><%= profile.email %></td>
        <td><%= profile.claimed %></td>
        <td><%= profile.description %></td>
        <td><%= profile.blurb %></td>
        <td><%= profile.bar_id %></td>
        <td><%= profile.state %></td>
        <td><%= profile.phone_number %></td>
        <td><%= profile.law_school %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div class="profile-header">
	<div class="container-fluid">
		<br />
		<div class ="row">
			<div class = "col-md-9">
				<div class ="avatar">
					<%= image_tag @profile.avatar.url(:medium), :class => "circular-image" %>
				</div>
				<div class = "profile-header"> 
					<h3><%= @profile.name %></h3>
				</div>
				<p class="meta">
					<small class="comment-user-height">Law School: <%= @profile.law_school%> | </small>
					<small class="comment-user-height">Bar Memberships: <%= @profile.state %> </small>
				</p>	
				<p class="bio"><%= @profile.blurb %> </p>
			</div>		
		</div>
	</div>	
</div>

<div class= "profile-content">
	<article id ="profile-tabs">
		<div class="ui responsive grid">
			<div class="col-md-12">
				<div class="tab-menu">
					<div class="tab">About</div>
					<div class="tab">Posts</div>
				</div>	
			</div>	
		</div>
	</article>

	<div class = "container-fluid">
		<div class="col-md-9">
			<div class = "section">
				<h3>About</h3>

					<p><%= @profile.description %> </p>
				
			</div>
		</div>
	</div>	
</div>