config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'registrations'}
  
  
  resources :quotes do
    resources :bids
  end
  resources :profiles

  resources :bids do
    resources :comments
  end

  resources :consultations

  match "quote", to: "quotes#quote", via: 'get'

  get "comments/index"

  get "comments/new"

  resources :states
  resources :seo_pages

  get 'divorce/:slug', to: 'states#show', as: 'state_show' 

  get ':state/:city/:id', to: 'seo_pages#show', as: 'seo_show'

  root to: 'tours#websites'

  scope '/lawyers' do
    get 'websites', to: 'tours#websites'
  end

  match "home", to: 'pages#home' , via: 'get'
    

end

app/models/bid.rb
class Bid < ActiveRecord::Base
	belongs_to :quote
	belongs_to :user
	has_many :comments, as: :commentable
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
	before_action :set_bid, only: [:show, :edit, :update, :destroy]
	before_action :set_quote, only: [:show, :new]
	before_filter :verify_vendor, only: [:new, :index]

	def new
		@bid = Bid.new

	    respond_to do |format|
	      format.html # new.html.erb
	      format.json { render json: @bid }
	    end
	end
	
	def create
		@bid = current_user.bids.new(bid_params)
		@bid.user_id = current_user.id
		@bid.quote_id = params[:quote_id]
			
	    respond_to do |format|
	      if @bid.save
	        format.html { redirect_to quote_bid_path(@bid.quote_id, @bid), notice: 'Your Bid Has Been Processed.' }
	        format.json { render action: 'show', status: :created, location: @bid }
	      else
	        format.html { render action: 'new' }
	        format.json { render json: @bid.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def show
		if signed_in?	
			if current_user.id == @bid.user_id || current_user.id == @quote.user_id	
				@commentable = @bid
				@comments = @commentable.comments
				@comment = Comment.new
			else
				redirect_to root_path
			end
		else
			redirect_to root_path
		end
	end

	def index
		@bids = current_user.bids.order("id DESC")
	end
	private

	def set_bid
		@bid = Bid.find(params[:id])
	end

	def set_quote
		@quote = Quote.find_by_id(params[:quote_id])
	end


	def bid_params
      params.require(:bid).permit(:user_id, :quote_id, :description, :amount, :name)
    end

end

app/views/bids/_form.html.erb
<div class="row">
	<div class="col-sm-8 col-sm-offset-3">
		<div class="quote-form">
			<h4> You're bidding on <%= @quote.name %>'s Request in <%= @quote.location %> </h4>
			<%= form_for [@quote, @bid] do |f| %>
					<div class="field">
					    <h3 class="quote_label">Enter Your Bid Title</h3>
					    <%= f.text_field :name, class: "quote_input" %>
			 		 </div>
			 		 <div class="field">
					    <h3 class="quote_label">Enter Your Bid Amount</h3>
					    <%= f.text_field :amount, class: "quote_input" %>
			 		 </div>
			 		 <div class="field">
					    <h3 class="quote_label">Describe The Service You Will Offer</h3>
					    <%= f.text_area :description, class: "quote_text_area", rows: 5 %>
			 		 </div>
				<%= f.submit "Submit Bid", class: "home2button" %>
			<% end %>
		</div>
	</div>
</div>

app/views/bids/index.html.erb
<div class="quote-header-show">
	<div class="container-fluid pad-top-bot">
		<div class="clearfix left">
			<a class="pic-padding left" style="width: 60px;">
				<img src="https://assembly.firesize.com/120x120/g_center/https://d1015h9unskp4y.cloudfront.net/attachments/bda9dba4-57d1-417e-a592-6fe5efbdd9d6/InstajobsLogo-01.jpg" width="60" height="60">
			</a>
			<div class="overflow-hidden">
				<h2 class="marg-bot-top-0">Caterer Dashboard</h2>
				<h4 class="marg-bot-top-0"><%= current_user.email %> </h4>
			</div>

		</div>
	</div>
	<div class="border-top">
		<div class="tab-container">
			<ul class= "new-nav--tabs">
				<li class="new-tab-unselect"><%= link_to "Quotes Available", quotes_path %></li>
				<li class="new-tab">Bids Placed</li>
			</ul>
		</div>
	</div>
</div>
<div class="container-fluid grey-quote-block">
	<div class="col-sm col-sm-8 px3">
		<div class="col-xs-12">
			<% @bids.each do |b| %>
				<div class="bg-white bid-shadow">
					<div class="bid-header">
						<h4><%= link_to b.name, quote_bid_path(b.quote_id, b)%></h4>
						<h4>Bid Amount: $<%= b.amount %> </h4>
					</div>
					<div class="border-top bid-header">
						<p><%= b.description %></p>
					</div>
					<div class="border-top bid-header">
						<div class="left" style="padding-right: 10px">
							<img class="bg-gray-6" src="https://gravatar.com/avatar/d377714ee6c1f97fa2c17ac9fa8825a9?d=https%3A%2F%2Fassembly.com%2Fassets%2Fdefault_avatar.png&amp;s=288" width="24" height="24" style="max-width:24px;max-height:24px;">
						</div>
						<div style="padding-bottom: 10px; padding-left: 5px;">
							<%= b.user.email %> submitted this Bid on <%= b.created_at.strftime("%b %d") %>
						</div>

					</div>
				</div>
			<% end %>


		</div>
	</div>
	<div class="col-sm col-sm-4 px3">
		
	</div>
</div>

app/views/bids/new.html.erb
<div class="container-fluid grey">
	<h1 class="quote-header">Place a Competitive Bid and Get More Business!</h1>
	<%= render 'form' %>
</div>

app/views/bids/show.html.erb
<div class="quote-header-show">
	<div class="container-fluid pad-top-bot">
		<div class="clearfix left">
			<a class="pic-padding left" style="width: 60px;">
				<img src="https://assembly.firesize.com/120x120/g_center/https://d1015h9unskp4y.cloudfront.net/attachments/bda9dba4-57d1-417e-a592-6fe5efbdd9d6/InstajobsLogo-01.jpg" width="60" height="60">
			</a>
			<div class="overflow-hidden">
				<h2 class="marg-bot-top-0"><%= @quote.name  %></h2>
				<h4 class="marg-bot-top-0"><%= @quote.location %> </h4>
			</div>

		</div>
	</div>
	<div class="border-top">
		<div class="tab-container">
			<ul class= "new-nav--tabs">
				<% if @quote.user_id == current_user.id %>
					<li class="new-tab-unselect"><%= link_to "Bids", quote_path(@quote) %>  </li>
				<% else %>
					<li class="new-tab-unselect"><%= link_to "Quotes Available", quotes_path %>  </li>
					<li class="new-tab-unselect"><%= link_to "Bids Placed", bids_path %>  </li>
				<% end %>
				<li class="new-tab"> Bid Overview  </li>

			</ul>
		</div>
	</div>
</div>
<div class="container-fluid grey-quote-block">
	<div class="col-sm col-sm-8 px3 bg-white">
		<div class="col-xs-12">
			<h4>Discuss and Finalize Your Catering Details Below</h4>
			<% if user_signed_in? %>
            	<%= render :partial => "comments/form" %>
            <% else %> 
            	<%= link_to "Sign Up to Comment", new_user_registration_path %>  
            <% end %>
            <%= render :partial => "comments/comments" %>
		</div>
	</div>
	<div class="col-sm col-sm-4 px3">
		<div class="bg-white bid-shadow">
			<div class="bid-header">
				<h2>Bidder Overview</h2>
				<h4><%= @bid.name %></h4>
				<h4>Amount Bid: $<%= @bid.amount %></h4>
			</div>
			<div class="border-top bid-header" style="padding-bottom: 10px;">
				<h4>Type: <%= @quote.field %></h4>
				<p><%= @bid.description %></p>
			</div>

		</div>
	</div>
</div>