config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'registrations'}
  
  
  resources :quotes do
    resources :bids
  end
  resources :profiles

  resources :bids do
    resources :comments
  end

  resources :consultations

  match "quote", to: "quotes#quote", via: 'get'

  get "comments/index"

  get "comments/new"

  resources :states
  resources :seo_pages

  get 'divorce/:slug', to: 'states#show', as: 'state_show' 

  get ':state/:city/:id', to: 'seo_pages#show', as: 'seo_show'

  root to: 'tours#websites'

  scope '/lawyers' do
    get 'websites', to: 'tours#websites'
  end

  match "home", to: 'pages#home' , via: 'get'
    

end

app/models/seo_page.rb
class SeoPage < ActiveRecord::Base
	extend FriendlyId
	friendly_id :name, use: :slugged 
end

app/controllers/seo_pages_controller.rb
class SeoPagesController < ApplicationController
  before_action :set_seo_page, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :verify_admin, only: [:new, :edit, :update, :destroy]
  # GET /seo_pages
  # GET /seo_pages.json
  def index
    @seo_pages = SeoPage.all
  end

  # GET /seo_pages/1
  # GET /seo_pages/1.json
  def show
    @lawyers = Profile.where(city: params[:city].capitalize).limit(10)
    @title = "Find the Best Divorce Lawyers in #{@seo_page.city}, #{@seo_page.state}."
  end

  # GET /seo_pages/new
  def new
    @seo_page = SeoPage.new
  end

  # GET /seo_pages/1/edit
  def edit
  end

  # POST /seo_pages
  # POST /seo_pages.json
  def create
    @seo_page = SeoPage.new(seo_page_params)

    respond_to do |format|
      if @seo_page.save
        format.html { redirect_to @seo_page, notice: 'Seo page was successfully created.' }
        format.json { render :show, status: :created, location: @seo_page }
      else
        format.html { render :new }
        format.json { render json: @seo_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seo_pages/1
  # PATCH/PUT /seo_pages/1.json
  def update
    respond_to do |format|
      if @seo_page.update(seo_page_params)
        format.html { redirect_to @seo_page, notice: 'Seo page was successfully updated.' }
        format.json { render :show, status: :ok, location: @seo_page }
      else
        format.html { render :edit }
        format.json { render json: @seo_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seo_pages/1
  # DELETE /seo_pages/1.json
  def destroy
    @seo_page.destroy
    respond_to do |format|
      format.html { redirect_to seo_pages_url, notice: 'Seo page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def verify_admin
    unless current_user.admin? == true
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seo_page
      @seo_page = SeoPage.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seo_page_params
      params.require(:seo_page).permit(:city, :state, :og_description, :slug, :image_tag, :name)
    end
end

app/helpers/seo_pages_helper.rb
module SeoPagesHelper
end

app/views/seo_pages/_form.html.erb
<%= form_for(@seo_page) do |f| %>
  <% if @seo_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seo_page.errors.count, "error") %> prohibited this seo_page from being saved:</h2>

      <ul>
      <% @seo_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :og_description %><br>
    <%= f.text_field :og_description %>
  </div>
  <div class="field">
    <%= f.label :image_tag %><br>
    <%= f.text_field :image_tag %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seo_pages/edit.html.erb
<h1>Editing Seo Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @seo_page %> |
<%= link_to 'Back', seo_show_path(@seo_page.state, @seo_page.city, @seo_page.name) %>

app/views/seo_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Seo Pages</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>State</th>
      <th>Og description</th>
      <th>Slug</th>
      <th>Image tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seo_pages.each do |seo_page| %>
      <tr>
        <td><%= seo_page.city %></td>
        <td><%= seo_page.state %></td>
        <td><%= seo_page.og_description %></td>
        <td><%= seo_page.slug %></td>
        <td><%= seo_page.image_tag %></td>
        <td><%= link_to 'Show', seo_show_path(seo_page.state, seo_page.city, seo_page.slug) %></td>
        <td><%= link_to 'Edit', edit_seo_page_path(seo_page) %></td>
        <td><%= link_to 'Destroy', seo_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seo page', new_seo_page_path %>

app/views/seo_pages/new.html.erb
<h1>New Seo Page</h1>

<%= render 'form' %>

<%= link_to 'Back', seo_pages_path %>

app/views/seo_pages/show.html.erb
  <div class="<%= @seo_page.image_tag %>">
    <div class="headline">
      <h1 class="home2headline w-hidden-tiny">We ranked the best Divorce Lawyers<br/>in <%= @seo_page.city %>, <%= @seo_page.state %>.</h1>
      <div class="subheaderhome2 ">Find the Best Lawyers in <%= @seo_page.city %>, <%= @seo_page.state %>.</div>
    </div>
  </div>
  <hr class="comments-rule">

  <% @lawyers.each do |l| %>
  <div class="profile-best"> 
    <div class="profile-body">
      <div class= "profile-user-name"><%= link_to( l.name, profile_path(l.id)) %>
      </div>
    
        <div class="profile-user-info">
        <small class="profile-user-height"><%= l.law_school %> | </small>
        <small class="profile-user-height"><%= l.city %> | </small>
        <small class="profile-user-height"><%= l.state %> </small>

        
      
      </div>
      <div class= "profile-image-container">
        <a class="user-image-link-post"><%=link_to( image_tag(l.avatar.url(:medium), :class => "circular-image-mini"), profile_path(l.id)) %> </a>

      </div>
      <div><%= l.blurb %></div>
    </div>

    <hr class ="comments-rule child">
  
  </div>  



  <% end %>